/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as libs from "./libs";
export { InterchainAccountRouter__factory } from "./InterchainAccountRouter__factory";
