/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  StandardHookMetadata,
  StandardHookMetadataInterface,
} from "../../../../../../@hyperlane-xyz/core/contracts/hooks/libs/StandardHookMetadata";

const _abi = [
  {
    inputs: [],
    name: "VARIANT",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60636037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806326418953146038575b600080fd5b603f600181565b60405161ffff909116815260200160405180910390f3fea164736f6c634300081b000a";

type StandardHookMetadataConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StandardHookMetadataConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StandardHookMetadata__factory extends ContractFactory {
  constructor(...args: StandardHookMetadataConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      StandardHookMetadata & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): StandardHookMetadata__factory {
    return super.connect(runner) as StandardHookMetadata__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StandardHookMetadataInterface {
    return new Interface(_abi) as StandardHookMetadataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): StandardHookMetadata {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as StandardHookMetadata;
  }
}
