/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GasRouter } from "./GasRouter";
export type { MailboxClient } from "./MailboxClient";
export type { Router } from "./Router";
